### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by myesn** [sindresorhus/import-modules#12]
This is an awesome project, and it would be great to get TypeScript support! 😊

**Comment by sindresorhus** [comment]
Pull request welcome. It should [follow this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide).

Some examples:
- https://github.com/sindresorhus/filled-array/commit/aae7539cb32f163cb063499664b012d0b04b3104
- https://github.com/sindresorhus/write-json-file/blob/main/index.d.ts
- https://github.com/sindresorhus/delay/blob/main/index.d.ts
