### ISSUE TITLE
some problems, please help me, thk

### ISSUE THREAD

**Issue by blazer233** [sindresorhus/import-modules#16]
https://github.com/sindresorhus/import-modules/blob/fc622bb003526da636f44dc0e581274568c61a26/index.js#L24

Why should define: `const done = new Set();` 

i think  
```js
 for(const i in returnValue){
    typeof i === 'string'
  }
 ```  

`if (done.has(filenameStem) ||`   can be replaced with   `if (!!returnValue[filenameStem]) ||`

**Comment by sindresorhus** [comment]
I'm not sure what you are proposing, but the proper way to propose changes is to submit a pull request (and making sure the tests pass with the change).
