### ISSUE TITLE
Jest modifies require.extensions

### ISSUE THREAD

**Issue by wrumsby** [sindresorhus/import-modules#2]
I'm writing a shareable ESLint config that uses [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) which uses this module.

Inspired by [Test Your ESLint config](https://medium.com/@michalozogan/test-your-eslint-config-1652e4cd48ec) I'm testing my config with Jest.

I was seeing failures around being able to load the eslint-plugin-unicorn rules and after looking at the code here and looking across tools I was using the problem I'm experiencing seems to be caused by facebook/jest#281.

While the problem is "caused by" Jest it seems like a difficult issue for Jest to resolve and I wondered if a solution might be possible in import-modules, e.g. 

```js
var extensions = Object.assign({}, {
    // Jest will redefine require.extensions to be {}
    // so add back default implementation(s) if not available
    '.js': require('default-require-extensions/js')
  }, require.extensions);

for (const ext of Object.keys(extensions)) {
  ...
```

A change like the above would mean that I get the default js implementation back and `rules` for eslint-plugin-unicorn load.

This is pretty similar to #1, but continues to use `require.extensions`.

**Comment by sindresorhus** [comment]
Sure, PR welcome.
