### ISSUE TITLE
typescript version

### ISSUE THREAD

**Issue by paragbaxi** [sindresorhus/import-modules#7]
In the future, I will attempt to fork and convert this to TS.

**Comment by sindresorhus** [comment]
I'm happy to add a index.d.ts, but I'm not interested in rewriting the whole package to TS.

If you do decide to submit a index.d.ts, ensure you adhere to https://github.com/sindresorhus/typescript-definition-style-guide

**Comment by felquis** [comment]
I've tried to use it with .ts files, but it returned an empty object instead.
